# Project information
site_name: DAVINCI MOBILE
site_description: 'DAVINCI MOBILE Anleitung'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.davinci-app.stueber.de'

# Copyright
copyright: © 2021 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.davinci-mobile.de'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Impressum
      link: https://www.stueber.de/imprint.php
    - label: Datenschutz
      link: https://legal.stueber.de/privacy.php

# Customization
extra_css:
    - assets/css/custom.css
    
# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
    - Überblick: index.md
    - Installation unter Android: installation-android.md
    - Installation unter iOS: installation-ios.md
    - Starten und Einstellen: start-and-config.md
    - So funktioniert die App: usage.md